// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace AssassinsGameplayTags
{
	ASSASSINS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Cancelable_Click);

	ASSASSINS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SetDestination_Click);

	ASSASSINS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Death);

    ASSASSINS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Channeling);
	ASSASSINS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dying);
	ASSASSINS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dead);

	ASSASSINS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
	ASSASSINS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataAvailable);
	ASSASSINS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataInitialized);
	ASSASSINS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);

	ASSASSINS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_Game);
	ASSASSINS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_GameMenu);
	ASSASSINS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_Menu);
	ASSASSINS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_Modal);
};